/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package caoss.simulator.parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int COMPUTATION = 1;
  /** RegularExpression Id. */
  int SYSCALL = 2;
  /** RegularExpression Id. */
  int MEM_LOAD = 3;
  /** RegularExpression Id. */
  int MEM_STORE = 4;
  /** RegularExpression Id. */
  int LOOP = 5;
  /** RegularExpression Id. */
  int DECIMAL_LITERAL = 6;
  /** RegularExpression Id. */
  int HEX_LITERAL = 7;
  /** RegularExpression Id. */
  int IDENTIFIER = 8;
  /** RegularExpression Id. */
  int LETTER = 9;
  /** RegularExpression Id. */
  int PART_LETTER = 10;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"computation\"",
    "\"syscall\"",
    "\"load\"",
    "\"store\"",
    "\"loop\"",
    "<DECIMAL_LITERAL>",
    "<HEX_LITERAL>",
    "<IDENTIFIER>",
    "<LETTER>",
    "<PART_LETTER>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"<\"",
    "\">\"",
    "\"{\"",
    "\"}\"",
  };

}
